# Generated by Django 4.1.5 on 2023-02-06 05:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('public_keys', '0001_initial'),
        ('auditors', '0001_initial'),
        ('control_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_authorized', models.BooleanField(default=True, verbose_name='is_authorized')),
                ('expiring_date', models.DateTimeField(default=datetime.datetime(2023, 2, 6, 7, 42, 15, 866436, tzinfo=datetime.timezone.utc), editable=False)),
                ('auditor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='auditors.auditor', verbose_name='auditor')),
                ('control_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='control_center.controlcenter', verbose_name='control_center')),
                ('public_key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='public_keys.publickey', verbose_name='public_key')),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
            },
        ),
    ]
