# Generated by Django 4.0.8 on 2023-01-31 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_alter_entry_is_producing_alter_entry_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='auditor',
            field=models.CharField(blank=True, max_length=128, verbose_name='auditor'),
        ),
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.CharField(blank=True, max_length=64, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, verbose_name=''),
        ),
    ]
