# Generated by Django 4.0.8 on 2023-01-27 01:46

from django.db import migrations, models
import django_extensions.validators
import public_keys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('key', public_keys.models.HexadecimalField(max_length=512, validators=[django_extensions.validators.HexValidator(length=256)], verbose_name='public key')),
            ],
            options={
                'verbose_name': 'public key',
                'verbose_name_plural': 'public keys',
            },
        ),
    ]
