# Generated by Django 4.0.8 on 2023-02-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publickey',
            name='cor_ver',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='verification coordinate B'),
        ),
        migrations.AddField(
            model_name='publickey',
            name='curve_a',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='curve a'),
        ),
        migrations.AddField(
            model_name='publickey',
            name='curve_b',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='curve b'),
        ),
        migrations.AddField(
            model_name='publickey',
            name='generator',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='generator A'),
        ),
        migrations.AddField(
            model_name='publickey',
            name='order_q',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='order q'),
        ),
        migrations.AddField(
            model_name='publickey',
            name='prime_p',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='prime number p'),
        ),
    ]
