# Generated by Django 4.0.8 on 2023-01-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("is_producing", models.BooleanField(verbose_name="is producing?")),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                "verbose_name": "entry",
                "verbose_name_plural": "entries",
            },
        ),
    ]
