# Generated by Django 4.0.8 on 2023-01-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='is_producing',
            field=models.BooleanField(blank=True, verbose_name='is producing?'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
