# Generated by Django 4.0.8 on 2023-01-31 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_keys', '0001_initial'),
        ('entries', '0003_entry_auditor_entry_date_alter_entry_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='ip_emisor',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='ip_emisor'),
        ),
        migrations.AddField(
            model_name='entry',
            name='ip_receptor',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='ip_receptor'),
        ),
        migrations.AddField(
            model_name='entry',
            name='public_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_keys', to='public_keys.publickey', verbose_name='public_key'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='is_producing',
            field=models.BooleanField(blank=True, null=True, verbose_name='is producing?'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='quantity'),
        ),
    ]
